//
//  FeedInteractor.swift
//  RedditFeed
//
//  Created by Danny on 8/20/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FeedBusinessLogic
{
    func fetchFeed(request: Feed.FetchFeed.Request)
}

protocol FeedDataStore
{
    //var name: String { get set }
}

class FeedInteractor: FeedBusinessLogic, FeedDataStore
{
    var presenter: FeedPresentationLogic?
    var worker = FeedWorker()
    //var name: String = ""
    
    // MARK: Fetch feed
    
    func fetchFeed(request: Feed.FetchFeed.Request)
    {
        worker = FeedWorker()
        worker.fetchFeed(afterLink: request.afterLink) { [weak self] posts, error in
            let response = Feed.FetchFeed.Response(posts: posts ?? [], error: error)
            self?.presenter?.presentFetchFeed(response: response)
        }
    }
}
