//
//  FeedWorker.swift
//  RedditFeed
//
//  Created by Danny on 8/20/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FeedWorker
{
    func fetchFeed(afterLink: String?, completion: @escaping(([Post]?, Error?) -> Void)) {
        let request = FeedRequest(after: afterLink)
        APIClient.shared.fetchFeed(
            request: request) { posts in
            DispatchQueue.main.async {
                completion(posts, nil)
            }
        } failure: { error in
            DispatchQueue.main.async {
                completion(nil, error)
            }
        }
    }
}
