//
//  FeedModels.swift
//  RedditFeed
//
//  Created by Danny on 8/20/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Feed
{
    // MARK: Use cases
    
    enum FetchFeed
    {
        struct Request
        {
            var afterLink: String?
        }
        struct Response
        {
            var posts: [Post]
            var error: Error?
        }
        struct ViewModel
        {
            var posts: [Post]
            var hasMore: Bool
            var error: String?
        }
    }
}
